version: '2.0'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/docker/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: miclefengzss
      MONGO_INITDB_ROOT_PASSWORD: 25456585

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: miclefengzss
      ME_CONFIG_MONGODB_ADMINPASSWORD: 25456585
