version: '3.1'

services:

  etcd:
    image: quay.io/coreos/etcd
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - /data/docker/etcd:/etcd-data
    environment:
      ETCD_NAME: node1
      ETCD_DATA_DIR: /etcd-data/etcd.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
